# These words, when used in a post, will be excluded from the words to be analyzed in order to determine how relevant a comment is to the post.
relevancy_exclusions = [
    "before", "where", "however", "shall", "though", "moreover", "therefore", "although", 
    "nevertheless", "nonetheless", "whereas", "whilst", "hereby", "herein", "thereby", 
    "furthermore", "consequently", "thereupon", "until", "since", "whereupon", 
    "notwithstanding", "albeit", "wherefore", "therein", "wherein", "whereby", 
    "subsequently", "insofar", "henceforth", "aforementioned", "thusly", "equally", 
    "initially", "increasingly", "predominantly", "alternatively", "invariably", 
    "comparatively", "presumably", "respectively", "perpetually", "inclusively", 
    "recurrently", "substantially", "principally", "accordingly", "exclusively", 
    "additionally", "significantly", "gradually", "remarkably", "unfortunately", 
    "affectionately", "voluntarily", "simultaneously", "historically", "consistently", 
    "tangibly", "relatively", "theoretically", "unpredictably", "naturally", 
    "extensively", "concurrently", "fundamentally", "conversely", "typically", 
    "dynamically", "hypothetically", "explicitly", "predictably", "habitually", 
    "unnecessarily", "incidentally", "undoubtedly", "unquestionably", "routinely", 
    "innocently", "importantly", "unsurprisingly", "objectively", "reliably", 
    "individually", "clearly", "generally", "inwardly", "logically", "inevitably", 
    "ultimately"
]

keyword_stuffing_exclusions = [
    "able", "bake", "ball", "band", "bank", "barn", "base", "bath", "bead", "beak", 
    "beam", "bees", "beer", "bell", "belt", "bend", "best", "bill", "bind", "bird", 
    "bite", "blow", "blue", "boat", "bore", "born", "boss", "bowl", "bush", "busy", 
    "call", "calf", "came", "camp", "card", "care", "cart", "case", "cast", "cat", 
    "cent", "chat", "chip", "city", "club", "coal", "coat", "cold", "come", "cool", 
    "cope", "core", "cork", "cost", "cous", "cove", "crab", "crag", "crop", "cubs", 
    "curl", "cute", "date", "dare", "dark", "dash", "data", "deal", "dear", "deck", 
    "dent", "desk", "dial", "diet", "died", "dine", "disk", "dock", "dogs", "doll", 
    "done", "door", "dose", "down", "drag", "draw", "drum", "dust", "duty", "east", 
    "easy", "edge", "else", "even", "evil", "exit", "fact", "fail", "fall", "fast", 
    "fate", "fear", "feed", "feel", "fell", "felt", "few", "find", "fire", "firm", 
    "fish", "flat", "flip", "flow", "folk", "food", "foot", "ford", "form", "four", 
    "free", "frog", "full", "game", "gain", "gale", "gasp", "gave", "gear", "gent", 
    "gill", "girl", "give", "goal", "gold", "gone", "good", "gore", "gray", "grip", 
    "grow", "guns", "half", "hall", "halo", "hand", "hang", "hard", "hark", "hate", 
    "have", "heal", "heap", "hear", "heat", "help", "here", "hero", "hill", "hint", 
    "hire", "hold", "hole", "holy", "hope", "horn", "hurt", "hush", "idea", "idle", 
    "inch", "info", "iron", "item", "jail", "jars", "join", "joke", "jump", "just", 
    "keen", "keep", "kind", "king", "kiss", "knee", "knot", "land", "late", "lava", 
    "lawn", "leak", "leap", "left", "lend", "less", "let", "life", "lift", "like", 
    "line", "link", "list", "live", "load", "long", "look", "loop", "lose", "love", 
    "luck", "made", "mail", "main", "make", "mall", "mark", "mate", "maze", "mead", 
    "mean", "meal", "meet", "meld", "melt", "menu", "mere", "mill", "mine", "miss", 
    "mood", "more", "most", "move", "name", "need", "nest", "news", "nice", "note", 
    "none", "nose", "null", "oak", "oath", "open", "over", "page", "paid", "pain", 
    "pair", "pale", "park", "part", "pass", "path", "peas", "pen", "per", "pest", 
    "pill", "pink", "pipe", "play", "plug", "plow", "pool", "port", "pose", "post", 
    "pull", "push", "pure", "race", "rage", "rail", "rain", "rake", "rant", "rare", 
    "rate", "read", "reef", "rest", "rich", "ride", "ring", "risk", "road", "roar", 
    "rock", "roll", "rope", "rose", "rush", "salt", "sand", "sash", "save", "scab", 
    "seal", "sell", "sent", "set", "sew", "shop", "shot", "show", "shut", "sick"
]
