spam_phrases = [
    "I enjoyed this",
    "I really enjoyed this",
    "Loved this post",
    "Enjoy this article",
    "Great post",
    "Great content",
    "Great article",
    "Excellent post",
    "Check out this link",
    "Check out the link",
    "Check this out",
    "Look at this link",
    "Visit now",
    "Visit this link",
    "Check this out now",
    "Visit this website",
    "Amazing content",
    "Incredible content",
    "Amazing post",
    "Unbelievable content",
    "You won’t believe this",
    "You won’t believe what happened",
    "This is unbelievable",
    "Click here",
    "Click the link",
    "Click this link",
    "Click to find out more",
    "Free gift",
    "Get your free gift",
    "Claim your free gift",
    "Get a free gift",
    "Limited time offer",
    "Limited time deal",
    "Special time offer",
    "Offer for a limited time",
    "Don’t miss out",
    "Don’t miss this offer",
    "Don’t miss your chance",
    "Don’t miss out on this",
    "Get yours today",
    "Get it today",
    "Get your free gift today",
    "Grab yours today",
    "Best deal ever",
    "Best deal for you",
    "Best deal available",
    "Get the best deal",
    "Act fast",
    "Act quickly",
    "Hurry up",
    "Act now",
    "Unbelievable results",
    "Incredible results",
    "Amazing results",
    "You won’t believe the results",
    "Hurry up",
    "Hurry before it’s gone",
    "Hurry while supplies last",
    "Rush to get it",
    "Sign up now",
    "Sign up today",
    "Sign up immediately",
    "Sign up for free",
    "Exclusive offer",
    "Exclusive deal",
    "Special offer",
    "Exclusive promotion",
    "Instant access",
    "Get instant access",
    "Access now",
    "Unlock instant access",
    "Special offer for you",
    "Special offer just for you",
    "Special offer exclusive to you",
    "Special offer only for you",
    "Exclusive offer just for you",
    "This offer is for you",
    "Guaranteed success",
    "Guaranteed win",
    "Guaranteed results",
    "Guaranteed improvement",
    "Free trial",
    "Try for free",
    "Free trial available",
    "Start your free trial",
    "Money back guarantee",
    "Risk-free guarantee",
    "Full refund guarantee",
    "Satisfaction guaranteed",
    "This will change your life",
    "This could change your life",
    "This can change your life",
    "Find out more",
    "Learn more",
    "Get more information",
    "Discover more",
    "Click to learn more",
    "Click to get more info",
    "Click here to find out more",
    "Find out how",
    "Earn money fast",
    "Make money fast",
    "Earn quick cash",
    "Earn money easily",
    "Make money online",
    "Earn money from home",
    "Start earning money",
    "Make fast money",
    "Investment opportunity",
    "Investment offer",
    "Investment deal",
    "Profitable investment",
    "Secrets revealed",
    "Secrets exposed",
    "Revealed secrets",
    "Unlock the secret",
    "Life-changing",
    "Life transforming",
    "Transform your life",
    "Change your life forever",
    "Hot offer",
    "Hot deal",
    "Limited hot offer",
    "Exclusive hot offer",
    "Just for you",
    "Just for you today",
    "Only for you",
    "Special for you",
    "Don’t wait",
    "Don’t hesitate",
    "Don’t delay",
    "Don’t waste time",
    "New product",
    "New arrival",
    "New release",
    "Latest product",
    "Get it now",
    "Get it today",
    "Buy it now",
    "Order now",
    "Save big",
    "Save a lot",
    "Save huge",
    "Save money",
    "Limited stock",
    "Stock is limited",
    "Limited availability",
    "Hurry, limited stock",
    "Exclusive deal",
    "Exclusive offer",
    "Private offer",
    "Special deal",
    "Congratulations you won",
    "Congratulations, you're a winner",
    "You have won",
    "Congrats, you won",
    "Special invitation",
    "Invitation just for you",
    "You're invited",
    "Exclusive invitation",
    "Be the first",
    "Be the first to know",
    "Be the first to get",
    "Be the first to try",
    "Don’t miss this chance",
    "Don’t miss this opportunity",
    "Don’t miss out",
    "Grab this chance",
    "Limited availability",
    "Limited time only",
    "Offer ends soon",
    "Only available for a short time",
    "Order now",
    "Place your order now",
    "Order today",
    "Buy today",
    "You are a winner",
    "You’ve won",
    "Congrats, you’ve won",
    "You won something special",
    "Act now and save",
    "Act now to save",
    "Hurry to save",
    "Save big when you act now",
    "Get free access",
    "Access for free",
    "Free access to this",
    "Unlock free access",
    "Exclusive access",
    "Special access",
    "VIP access",
    "Access granted",
    "Unlock your reward",
    "Claim your reward",
    "Get your reward",
    "Your reward is waiting",
    "You're just one click away",
    "One click away",
    "Just one click",
    "It’s just a click away",
    "This could be yours",
    "This is yours",
    "This is all yours",
    "It’s yours to claim",
    "Get your free gift",
    "Claim your free gift",
    "Get your gift now",
    "Free gift waiting for you",
    "Instant reward",
    "Immediate reward",
    "Claim your instant reward",
    "Get your instant reward",
    "Click and win",
    "Win now",
    "Win with just one click",
    "Click here to win",
    "Don’t miss out on this opportunity",
    "Don’t miss this opportunity",
    "This is your chance",
    "This is your opportunity",
    "Free download",
    "Download for free",
    "Get your free download",
    "Instant download available",
    "Click to receive",
    "Get your download",
    "Click to get it",
    "Get the download now",
    "Exclusive offer just for you",
    "This exclusive offer is just for you",
    "An offer just for you",
    "This is for you only",
    "This offer ends soon",
    "This offer is closing soon",
    "Hurry, the offer ends soon",
    "Act fast, offer ends soon",
    "Grab it before it's gone",
    "Get it before it’s gone",
    "Get it while it lasts",
    "Hurry, it’s almost gone",
    "Best price ever",
    "Lowest price ever",
    "Unbeatable price",
    "Unbelievable price",
    "The secret to success",
    "The key to success",
    "Success revealed",
    "The path to success",
    "Start today",
    "Start now",
    "Start today and change your life",
    "Get started today",
    "Act now",
    "Hurry now",
    "Take action now",
    "Don’t wait, act now",
    "You’ve been selected",
    "Congratulations, you’ve been selected",
    "You’ve been chosen",
    "You’re one of the selected",
    "Offer expires soon",
    "This offer expires soon",
    "This deal expires soon",
    "Offer ends soon",
    "Just for you",
    "Only for you",
    "Specially for you",
    "Exclusively for you",
    "Sign up for free",
    "Sign up and get started",
    "Sign up today",
    "Sign up now and get started",
    "Don’t miss this opportunity",
    "Don’t wait, act now",
    "This is your chance",
    "Claim your prize now",
    "Claim your spot",
    "Claim your reward",
    "Secure your spot",
    "Secure your reward",
    "Special reward",
    "Exclusive reward",
    "Claim your special reward",
    "Unlock your special reward",
    "Limited quantity",
    "Only a few left",
    "Limited availability",
    "Hurry, only a few left",
    "Get your discount",
    "Claim your discount",
    "Grab your discount",
    "Unlock your discount",
    "See for yourself",
    "Check it out",
    "Take a look",
    "Take a peek",
    "New opportunity",
    "New chance",
    "Don’t miss the new opportunity",
    "Get in on the new opportunity",
    "Access now",
    "Unlock now",
    "Get instant access",
    "Unlock your opportunity",
    "Unlock your chance",
    "Don’t miss your chance",
    "Take advantage of this",
    "Get started now"
]
